name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - run: nix-build
      - name: upload build results
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: result/.
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: for tarball in result/*; do npm publish --access public --verbose ./$tarball; done;
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
